### ISSUE TITLE
Please get into melpa so it is easy to install

### ISSUE THREAD

**Issue by wakatara** [fuxialexander/org-pdftools#14]
This looks pretty interesting. Can you get it into melpa or one of the other package repos so that it can be installed easily. Someone mentioned it in a possting somewhere and I came to check it out but was a bit awwwww when I could not install it easily via altering my init.el.  =] 

lemme know!
ciao!
Daryl

**Comment by mohkale** [comment]
have you looked into the [straight](https://github.com/raxod502/straight.el) package manager, it makes issues painless.

**Comment by randomwangran** [comment]
or try git submodule like this user: https://github.com/manateelazycat/lazycat-emacs/blob/master/.gitmodules

**Comment by fuxialexander** [comment]
submitted https://github.com/melpa/melpa/pull/6702
finger crossed

**Comment by randomwangran** [comment]
take it easy, for sure it will pass, this is awsome piece package!

**Comment by fuxialexander** [comment]
Sorry for the long delay. Finally this package is on the MELPA!
