### ISSUE TITLE
bump required org-version

### ISSUE THREAD

**Issue by mohkale** [fuxialexander/org-pdftools#18]
I'm unable to require this package because it depends on `org-refile.el` which was [introduced](https://github.com/bzg/org-mode/commits/master/lisp/org-refile.el) under a month ago.

Is it an essential require? I removed the require call from the file to load it and everything's working fine on my end so far.

**Comment by fuxialexander** [comment]
https://github.com/fuxialexander/org-pdftools/issues/20
https://github.com/fuxialexander/org-pdftools/commit/5a393dba1db318bb3437e36080483d62089aa363

Please try whether it works now. I added this when emacs gives me an error after byte-compilation. But the error disappears now.
