### ISSUE TITLE
当pdf名称中存在空格的时候，获取的链接会断开，从而失效

### ISSUE THREAD

**Issue by xiaolaoc** [fuxialexander/org-pdftools#23]
<img width="897" alt="Snipaste_2020-04-06_10-40-31" src="https://user-images.githubusercontent.com/20012636/78518462-20d7e700-77f3-11ea-902e-660448cb877c.png">

**Comment by xiaolaoc** [comment]
我的文献重命名按照文章标题，其中有空格，但是这样就不能点击跳转了

**Comment by fuxialexander** [comment]
Ohh我尽快修复一下 

（ps 发现同行了lol

**Comment by fuxialexander** [comment]
Ohh我尽快修复一下 

（ps 发现同行了lol

**Comment by xiaolaoc** [comment]
> Ohh我尽快修复一下
> 
> （ps 发现同行了lol
hh

**Comment by xiaolaoc** [comment]
> > Ohh我尽快修复一下
> > （ps 发现同行了lol

今天就回复了哈，作者速度好快啊。不是同行，我是用你的那个demo里的那个pdf实验的，一开始没有空格不会断开，后来用我自己的bib里的试验时发现了。

**Comment by fuxialexander** [comment]
我思考了一下 因为默认用org-insert-link的时候插入的是[[description][link]] 这样的format，不会被空格影响 而在这个properties里的是只有link本身这部分 所以会被空格破坏
其实可以先用org-noter这个函数打开一个org-noter session 然后在对应的heading上用`org-noter-sync-current-note` (C-M-i)

不过我会看看能不能把这个link改成[[link]]的形式

**Comment by fuxialexander** [comment]
fixed in https://github.com/fuxialexander/org-pdftools/commit/e01273322a36941ee8ea0e31f9a47b9d08ea91a8
