### ISSUE TITLE
org version this package depends on

### ISSUE THREAD

**Issue by zbelial** [fuxialexander/org-pdftools#24]
I noticed that this package depends on org 9.3.6, which is not even included in emacs-27 branch  and can only be installed from elpa. 
Are there any features in org 9.3.6 that this package needs but are not found in an older version of org ?

I think it's better if this package can be used with builtin org in emacs 26 at least.

**Comment by fuxialexander** [comment]
I noticed that you just forked the repo. If possible would you mind have a test on Emacs 26? Currently, I don't have an installation of Emacs 26 so it would be great if you could test and report whether there is any issue.

**Comment by zbelial** [comment]
Now I can only test this package on Emacs 27 with the bundled org as this is the version I'm using, but I think I can test it on Emacs 26 later.
I'll give you feedback then.

Thanks.
