### ISSUE TITLE
Issues creating org-noter skeleton from PDF annotations

### ISSUE THREAD

**Issue by edpotts** [fuxialexander/org-pdftools#33]
When I run M-x org-noter-create-skeleton, specifically to export annotations, I get the following error:

org-noter-pdftools--pretty-print-location: Wrong type argument: org-noter-pdftools--location, nil

Any suggestions gratefully received.

**Comment by fuxialexander** [comment]
can you try `org-noter-pdftools-create-skeleton` and see whether the bug exist?

**Comment by edpotts** [comment]
> can you try `org-noter-pdftools-create-skeleton` and see whether the bug exist?

With this I get:

> Should we insert the annotations contents? (y or n) y
funcall-interactively: Symbol’s value as variable is void: org-noter-pdftool-link-generator

**Comment by UndeadKernel** [comment]
I'm observing the same problem.
Where is the variable `org-noter-pdftool-link-generator` supposed to be defined?

**Comment by fuxialexander** [comment]
@UndeadKernel It should be in the customize setting, I think I've left a default their?

**Comment by zoechi** [comment]
`describe-variable` does not list `org-noter-pdftool-link-generator` for me

**Comment by torfjelde** [comment]
Just adding to this; also not working for me and `org-noter-pdftool-link-generator` doesn't exist :confused:

**Comment by dragarok** [comment]
I am also facing the same issue and fabanados's change is not also working for me. The same issue is referenced there as well.

**Comment by Ypot** [comment]
Maybe related with this?

https://github.com/fuxialexander/org-pdftools/issues/47

**Comment by BFAnas** [comment]
Also Having the same problem, anyone of you was able to find a fix??

**Comment by BFAnas** [comment]
> Maybe related with this?
> 
> #47

Hello i was having the same problem, then I updated the org-pdftools.el and org-noter-pdf-tools, and used `org-noter-pdftools-create-skeleton` instead of `org-noter-create-skeleton` and all went well.

Hope it is useful for anyone with this problem.
