### ISSUE TITLE
README: org-pdftools hook

### ISSUE THREAD

**Issue by firmart** [fuxialexander/org-pdftools#36]
In the README configuration
```elisp
(use-package org-pdftools
  :hook (org-load . org-pdftools-setup-link))
```
The hook has no effect to me (i.e. cannot find a `pdf` entry in `org-link-parameters`). Not sure what the documentation means by "when `org.el` is loaded" since org-mode is byte-compiled. Anyway, I changed the hook to `org-mode` and the issue is gone.  

```elisp
(use-package org-pdftools
  :hook (org-mode . org-pdftools-setup-link))
```

**Comment by timmli** [comment]
I can confirm this.  I'm instead using

	(use-package org-pdftools
		:config
		(with-eval-after-load 'org
			(org-pdftools-setup-link))
		))
