### ISSUE TITLE
Add to README/Usage "requires :ensure t" in use-package section.

### ISSUE THREAD

**Issue by wilya7** [fuxialexander/org-pdftools#39]
Concerning the readme, without `:ensure t` use-package would give me an error and would not load org-note-pdftools.

**Comment by TimQuelch** [comment]
This is nothing to do with this package.

`use-package` is not a package manager. Having a `use-package` statement  does not automatically install the package, this must be done with the `package` functions. `use-package` includes `:ensure` to automatically ensure that the package is installed as well. Therefore if you don't want to manually install packages using `package-install`, you must include `:ensure t` in the use package statement or set `use-package-always-ensure` to `t`.

**Comment by wilya7** [comment]
I understand that, and I appreciate the clear explanation you provided. I opened an issue mainly referring to the readme file. As it as a section specifically describing [the installation with use-package](https://github.com/fuxialexander/org-pdftools#usage), I suggest that it would be useful to include also that part of the configuration.
