### ISSUE TITLE
Error when installing from Melpa

### ISSUE THREAD

**Issue by AtomicNess123** [fuxialexander/org-pdftools#40]
`: pdf-info-epdfinfo-program is not executable`

When attempting to install from Melpa.
Any ideas?

**Comment by zsaur** [comment]
> `: pdf-info-epdfinfo-program is not executable`
> 
> When attempting to install from Melpa.
> Any ideas?

Run pdf-tools-install after installing the package via emacs.
from: https://github.com/politza/pdf-tools/issues/288

**Comment by zsaur** [comment]
@fuxialexander I also went trough the same trouble from this issue. Do you think you could make more obvious one needs to run `pdf-tools-install` after installing?

(thanks for this awesome project!)
