### ISSUE TITLE
`Package org-noter-pdftools is incompatible.

### ISSUE THREAD

**Issue by pauljamesharper** [fuxialexander/org-pdftools#41]
I am on Debian 10 with the latest Emacs and Org-Mode built from Source. M-x org-version:

`Org mode version 9.3 (release_9.3 @ /usr/local/share/emacs/28.0.50/lisp/org)`  

I got the message that Package org-noter-pdftools is incompatible. Is there a workaround for this? 

Is there something I can do to give your more information for diagnostics?

```
`Package org-noter-pdftools is incompatible.

     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa
    Version: 20200418.929
     Commit: 8cc15bb8014ed1f047eecc0abd8bf447f86c0505
    Summary: Integration between org-pdftools and org-noter
   Requires: emacs-26.1, org-9.4 (not available), pdf-tools-0.8, org-pdftools-1.0, org-noter-1.4.1
   Homepage: https://github.com/fuxialexander/org-pdftools
   Keywords: convenience 
 Maintainer: Alexander Fu Xi <fuxialexnader@gmail.com>
     Author: Alexander Fu Xi <fuxialexander@gmail.com>

Add integration between org-pdftools and org-noter.`
```

**Comment by xl666** [comment]
Same problem here. I believe this is a bug in the package requeriments, stating org-9.4, but most recent stable version is 9.3.7

**Comment by paigenorth** [comment]
I am having the same problem.

**Comment by fuxialexander** [comment]
now it's depending on 9.3.6
