### ISSUE TITLE
org-load-hook didn't work for me to get the `pdf:` link set up

### ISSUE THREAD

**Issue by zoechi** [fuxialexander/org-pdftools#42]
After this change it worked
```elisp
(use-package
  org-pdftools
  :after org
  :config (org-pdftools-setup-link))
  ;; :hook (org-load . org-pdftools-setup-link))
```
I'm not proficient enough in Emacs to know if this is a good solution.

A wild guess is that it might be related to straight.el, but I haven't tried without.

**Comment by wilya7** [comment]
Duplicate of #36
