### ISSUE TITLE
Storing link to page sometimes takes long for large PDFs

### ISSUE THREAD

**Issue by heyarne** [fuxialexander/org-pdftools#43]
I would like to link to specific pages in PDFs that can become quite heavy (> 150mb). I answer both prompts with `n` and sometimes get the message "reminder: you haven't performed an isearch". Sometimes this message does not appear and I have not been able to reproduce when it happens. Whenever the message appears emacs freezes for a couple of seconds, in other cases it remains responsive and I can directly paste the link into an org file. Why does the message sometimes appear and sometimes not? Can I somehow force consistent behavior?

**Comment by fuxialexander** [comment]
The isearch link functionality is a bit unstable. Basically if you have used isearch to search for some text, you won't get that message. You can disable the isearch link function using the new customizable `org-pdftools-use-isearch-link`
