### ISSUE TITLE
pdf-view buffer unusable after enabling org-noter

### ISSUE THREAD

**Issue by oatmealm** [fuxialexander/org-pdftools#49]
Hi. Thanks for taking the time to develop this extension. Love the idea!

I've followed the setup instructions. After I enable org-noter I'm immediately prompted to decide if I want to add a note. When entering 'n' I'm propped again for a search. 

Any click or key press, including page up or down re-prompts and I can't use the buffer containing the pdf I've opened.

**Comment by saminahbab** [comment]
I am suffering from the same issue. Checking the variables, i cant see any config to turn this off either, every time i press n for next page, the dialog opens up,

**Comment by andrew-christianson** [comment]
Seeing this as well

**Comment by fuxialexander** [comment]
Duplicate with https://github.com/fuxialexander/org-pdftools/issues/60 and should've been fixed with newest usage instruction
