### ISSUE TITLE
pdf: link export description to `nil` 

### ISSUE THREAD

**Issue by firmart** [fuxialexander/org-pdftools#58]
It happens that all my `pdf:` links are exported to a `nil` link, *i.e.* the description is replaced by `nil`. This can be checked for instance with `org-latex-export-as-latex`: description are exported as `nil` in LaTeX. But this issue is present for other export type. It occurs even for `pdf:` link without description.

I checked the code source, and the function `org-pdftools-export` looks standard. I put a `(message "%s" desc)` inside that function, and it always outputs `nil`. Very weird issue. It's not an Org mode bug, because all other link export description correctly.

emacs version: emacs 28.0.50
org version: 9.4
package version: 20200422.1350

**Comment by fuxialexander** [comment]
Do you have link desc in your link? As in desc in `[[link][desc]]`

**Comment by firmart** [comment]
Somehow the bug is not present anymore (package version: 20210110.2052) , and I can't say why. The link I was talking about is of the form `[[pdf:/path/to/file.pdf::35][desc]]`. I think that you can close this issue.
