### ISSUE TITLE
How can I get the marked text in a pdf file?

### ISSUE THREAD

**Issue by chriad** [fuxialexander/org-pdftools#59]
I have a capture template that stopped working but I don't understand why.

```
(defun org-capture-pdf-active-region ()
  "Capture the active region of the pdf-view buffer."
  (let* ((pdf-buf-name (plist-get org-capture-plist :original-buffer))
         (pdf-buf (get-buffer pdf-buf-name)))
    (if (buffer-live-p pdf-buf)
        (with-current-buffer pdf-buf
          (car (pdf-view-active-region-text)))
      (user-error "Buffer %S not alive." pdf-buf-name))))
```

I use the following template:

```
("pc" "Drill cloze pdf" entry (file+headline "~/Documents/wiki/drill.org" "drills")
                             "** :cloze:drill:\n%(org-capture-pdf-active-region)%?\n%a\n")
```
This yields the following org entry:

```
** :cloze:drill:
%![Error: (error The region is not active)]
[[pdf:<path to pdf>:36++0.00;;annot-36-7][<name of pdf>.pdf: Page 36; Quoting: <text from active region>]]
```
So the link works as expected and the text from the active region is part of the link, but it is not captured by the function `org-capture-pdf-active-region` which I use in the capture template.

Do you have a suggestion how I could get the highlighted text from the pdf?
If I change the function `org-pdftools-get-desc-default` like this:

```
(defun org-pdftools-get-desc-default (file page &optional text)
  (concat "" text)
```
then the active region is captured but the link doesn't work anymore.

**Comment by fuxialexander** [comment]
That's because once org-pdftools is used to get a link, a new annotation is created. And then the highlighted region will not be hightlighted any more. It's the behavior of pdftools and I cannot do much about it.
However you can check whether there is a way to get the text before the link is created.
