### ISSUE TITLE
"You can click anywhere on the page to add a link to. Do you want to do that?" keeps popping up

### ISSUE THREAD

**Issue by cryoguy** [fuxialexander/org-pdftools#60]
Did anyone have this issue? When I start org-noter, "You can click anywhere on the page to add a link to. Do you want to do that?" keeps popping up.  I am using Emacs 27.1 with Arch Linux.

**Comment by cryoguy** [comment]
Look likes  I am not alone.  It's been reported [here](https://github.com/weirdNox/org-noter/pull/93) with a patch!

**Comment by gabrielgesteira** [comment]
Could you fix it using the patch?
I am having the same issue, and the patch didn't work for me (Emacs 26.3).

**Comment by cryoguy** [comment]
@gabrielgesteira the el-patch one worked for me (Emacs 27.1)

**Comment by gabrielgesteira** [comment]
Great! I'll try that again after upgrading Emacs. Thank you!

**Comment by LorenRiccie** [comment]
same here! (Emacs 27.1)

**Comment by fuxialexander** [comment]
Should be fixed if you follow the new usage instruction in the README
