### ISSUE TITLE
org-noter-insert-precise-note stopped working after installing org-pdftools

### ISSUE THREAD

**Issue by RetepRennelk** [fuxialexander/org-pdftools#63]
Steps for reproduction:
- Select text in a pdf
- Call `org-noter-insert-precise-note` or `org-noter-pdftools-insert-precise-note`
- Leave the prompt `Note: ` empty, i.e., just hit return
- Gets the error `let: Wrong type argument: listp, #s(org-noter-pdftools--location...` 
- Despite the thrown error, the text in the pdf is highlighted without any trace in the org-file, thus, adding insult to injury :)

Expected behavior: 
- The selected text is highlighted and copied into the notes org-file annotated with links back to the original.

Observations:
The variable `location` in org-noter.el is a simple cons cell with x and y value. But after installing org-pdftools, `location` turns into a `cl-defstruct `with type `org-noter-pdftools--location`. And this crashes due to the frequent use of `(car location)` which won't work on a `cl-defstruct`. The problem persists with `org-noter-pdftools-insert-precise-note` from the readme. 

Please help!

**Comment by fuxialexander** [comment]
I cannot reproduce your problem following the step above actually

**Comment by RetepRennelk** [comment]
Solved it! It was not clear from the documentation, that org-noter.el needs to be changed as well. I applied the change described in  
https://github.com/weirdNox/org-noter/pull/93/commits/f8349ae7575e599f375de1be6be2d0d5de4e6cbf and it works now. Thanks!

**Comment by RetepRennelk** [comment]
In order to make `org-noter-pdftools-insert-precise-note` work as described above, a single change in `org-pdftools-get-link` is required, i.e., a change from `(pdf-view-active-region t)` to `(pdf-view-active-region)`.

If `pdf-view-active-region` is called with a non-nil argument (as it is currently), the selected region will be deactivated after running `org-pdftools-get-link`. And this prevents `org-noter-insert-note` to retrieve the previously selected text by calling `pdf-view-active-region-text`, which then can also not be inserted as a new heading. 

Having reviewed the code quite a bit, it feels strange that the current implementation should work for you as is, i.e., without this change.

**Comment by fuxialexander** [comment]
Thanks for your comment! Indeed org-noter was not able to retrieve the selected text as title due to the region be deactivated. I thought I set that explicitly to `t` for some reason but cannot remember it anymore. So I'll change it to `nil` for now. 

However, I still don't quite understand how this issue is related to the `location` format and why I don't have the error warning. I'm on Linux with Emacs 28 so it could be a platform-specific thing.

**Comment by roy-tancredi** [comment]
I currently have similar problem - after steps specified by @RetepRennelk:
> Steps for reproduction:
>
>  - Select text in a pdf
>  - Call org-noter-insert-precise-note or org-noter-pdftools-insert-precise-note
>  - Leave the prompt Note: empty, i.e., just hit return 

I get ```image-mode-window-get: Wrong type argument: listp, t``` 

I inspected that there is no ```(pdf-view-active-region t)``` in ```rg-pdftools-get-link``` definition. Can you help me guys with that? Or if there is need for more info please give me guidelines for that.

org-noter-pdftools version: 20210118.1611
org-noter version: 20191020.1212
pdf-tools version : 20200512.1524
Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2021-04-04, unofficial emacs-snapshot build: http://emacs.ganneff.de/, git commit dd5ba88afbb63f54603cc632fc55993c04531a85
OS: Debian GNU/Linux 10 (buster)
