### ISSUE TITLE
How to link link pdf files from this package?

### ISSUE THREAD

**Issue by JunHoo-Lee** [fuxialexander/org-pdftools#76]
Hi there,

I wanted to link pdf files in .org files but error occur to me, what is the actual prefix of pdf file?

I tried total 3 types of prefix, but it doesn't work,

1. [[pdfview:**filename**::1][name]]
2. [[pdf:**filename**::1][name]]
3.  [[pdftools:**filename**::1][name]]

and it says : 

![image](https://user-images.githubusercontent.com/37990603/129846740-3eb95224-98dd-4de4-bcd4-24a8a9449a25.png)

I'm using doom emacs in macos,  packages are installed as follows
![image](https://user-images.githubusercontent.com/37990603/129846569-dc60d6f1-f63e-4d3d-8876-c1870d3399f0.png)

please save me..

**Comment by crlsh** [comment]
Just use org-store-link on the pdf page and org-insert-link where you want to insert it.
Make sure you are using org-pdftools-setup-link in the emacs configuration if it does not work.
The prefix is ​​pdf and can be changed by customizing org-pdftools-link-prefix

**Comment by JunHoo-Lee** [comment]
Thank you for your kindness! I think i misunderstood config option, I thought installation is over when i just install an org-pdftools package, and no need to modify config file.
